# See https://redocly.com/docs/cli/configuration/ for more information.
organization: Pontue
apis:
  main@v2:
    root: ./openapi/openapi.yaml
rules:
  no-unused-components: error
  no-ambiguous-paths: off
theme:
  openapi:
    pagination: section
    hideTryItPanel: false
    hideDownloadButton: true
    showConsole: true
    htmlTemplate: ./docs/index.html
    theme:
      layout:
        showDarkRightPanel: true
      colors:
        primary:
          main: '#FFFFFF'
      sidebar:
        backgroundColor: '#592A96'
        textColor: '#FFFFFF'
        activeBgColor: '#694596'
        activeTextColor: '#FFFFFF'
      rightPanel:
        backgroundColor: '#592A96'
        panelBackgroundColor: '#694596'
        panelControlsBackgroundColor: '#3a2c47'
        textColor: '#FFFFFF'
      typography:
        links:
          color: '#0000FF'
          visited: '#800080'
