# See https://redocly.com/docs/cli/configuration/ for more information.
organization: Pontue
apis:
  main@v2:
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
    no-ambiguous-paths: off
features.openapi:
  hideTryItPanel: false
  hideDownloadButton: true
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: '#592a96'
